import type { Category, DiagnosisResult } from '@/types/app';

export const CATEGORIES: Category[] = [
  { id: 'ceiling', icon: '\u{1F528}', label: 'Ceiling & Drywall', sub: 'Patches, cracks, water stains', clr: '#8D6E63' },
  { id: 'plumbing', icon: '\u{1F527}', label: 'Plumbing', sub: 'Leaks, clogs, fixtures', clr: '#1565C0' },
  { id: 'painting', icon: '\u{1F3A8}', label: 'Interior Painting', sub: 'Walls, trim, prep work', clr: '#C05E14' },
  { id: 'lawn', icon: '\u{1F33F}', label: 'Lawn & Landscape', sub: 'Mowing, beds, irrigation', clr: '#2D8A4E' },
  { id: 'deck', icon: '\u{1FAB5}', label: 'Deck & Patio', sub: 'Staining, boards, railings', clr: '#6D4C41' },
  { id: 'electric', icon: '\u26A1', label: 'Electrical', sub: 'Outlets, switches, fixtures', clr: '#F9A825' },
  { id: 'hvac', icon: '\u2744\uFE0F', label: 'HVAC', sub: 'Filters, thermostats, ducts', clr: '#0097A7' },
  { id: 'tile', icon: '\u{1F532}', label: 'Tile & Flooring', sub: 'Grout, cracks, replacement', clr: '#5D4037' },
  { id: 'appliance', icon: '\u{1F50C}', label: 'Appliance Repair', sub: 'Fridge, washer, dishwasher', clr: '#455A64' },
  { id: 'window', icon: '\u{1FA9F}', label: 'Windows & Doors', sub: 'Seals, hardware, screens', clr: '#00796B' },
  { id: 'roofing', icon: '\u{1F3E0}', label: 'Roofing & Gutters', sub: 'Shingles, leaks, cleaning', clr: '#E64A19' },
  { id: 'concrete', icon: '\u{1F9F1}', label: 'Concrete & Masonry', sub: 'Cracks, patching, sealing', clr: '#757575' },
];

export const DIAGNOSES: Record<string, DiagnosisResult> = {
  ceiling: {
    title: 'Patching a Drywall Hole',
    conf: 82,
    xp: 50,
    save: 15000,
    why: 'Drywall patching is one of the most approachable DIY repairs. With a patch kit and basic tools, most homeowners can achieve a professional-looking result on small to medium holes. The key is patience with the mudding and sanding stages.',
    flags: [],
    fq: [
      { q: 'How large is the damaged area?', opts: ['Nail hole (< 1 inch)', 'Small hole (1-3 inches)', 'Medium hole (3-6 inches)', 'Large hole (> 6 inches)'] },
      { q: 'Where is the damage located?', opts: ['Wall — easy to reach', 'Wall — above 8 feet', 'Ceiling', 'Near a corner or edge'] },
      { q: 'What texture does the surrounding wall have?', opts: ['Smooth / flat', 'Orange peel', 'Knockdown', 'Popcorn / heavy texture'] },
      { q: 'Have you done drywall work before?', opts: ['Never', 'Once or twice', 'Several times', 'Experienced'] },
    ],
    diy: { lo: 2500, hi: 6000, hrs: 3, time: '2-3 hours', risk: 'Low. Worst case is a visible patch that needs another coat of mud and sanding.' },
    pro: { lo: 15000, hi: 30000, time: '1-2 hours', risk: 'Minimal — professionals handle texture matching and paint blending.', note: 'Most drywall contractors have a minimum service call fee of $100-$150, which makes small patches expensive per hole.', script: 'Hi, I have a drywall hole that needs patching. It\'s about [size] inches wide on a [wall/ceiling] with a [smooth/textured] finish. Could you provide an estimate for patching and painting to match? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Prep & cut damaged area', time: '20 min' },
      { phase: 'Install backing & patch', time: '20 min' },
      { phase: 'First mud coat & dry', time: '45 min' },
      { phase: 'Second coat & dry', time: '45 min' },
      { phase: 'Sand & prime', time: '20 min' },
      { phase: 'Paint & clean up', time: '15 min' },
    ],
    tools: [
      { n: 'Putty Knife (6")', e: '\u{1FA9B}', r: 'Required', tip: 'A flexible 6-inch knife spreads mud more smoothly than a narrow one. Keep the edge clean between passes.' },
      { n: 'Sanding Block', e: '\u{1F9F1}', r: 'Required', tip: 'Use 120-grit for rough sanding, then 220-grit for a smooth finish. A sanding sponge works great around edges.' },
      { n: 'Utility Knife', e: '\u{1FA9A}', r: 'Required', tip: 'Score a clean rectangle around the damage rather than trying to patch an irregular shape.' },
      { n: 'Drill/Driver', e: '\u{1FA9B}', r: 'Recommended', tip: 'Needed to attach backing board screws. A cordless drill makes this much faster.' },
      { n: 'Drywall Saw', e: '\u{1FA9A}', r: 'Required', tip: 'A jab saw lets you cut drywall without a pilot hole. Keep the blade perpendicular for clean edges.' },
    ],
    steps: [
      { s: 'Cut out the damaged area in a clean rectangle using a utility knife and drywall saw. Remove any loose debris.', t: '15 min', photo: true, tip: 'Mark your cut lines with a pencil and straightedge first. A clean rectangle is much easier to patch than an irregular shape.' },
      { s: 'Install a backing board (furring strip or plywood) behind the opening and secure with drywall screws.', t: '15 min', photo: true, tip: 'The backing board should extend at least 2 inches past each side of the opening. Screw through the existing drywall into the backer.' },
      { s: 'Cut a drywall patch to fit the opening and screw it to the backing board. Apply self-adhesive mesh tape over all seams.', t: '15 min', photo: true, tip: 'Cut the patch slightly undersized (1/8 inch gap) for a better mud joint. Don\'t overtighten screws — just dimple the surface.' },
      { s: 'Apply the first coat of joint compound over the tape and seams. Feather edges out 4-6 inches. Allow to dry completely.', t: '45 min', photo: false, tip: 'Thin coats are better than thick ones. The first coat doesn\'t need to be perfect — it\'s a base layer. Allow 30-45 minutes to dry.' },
      { s: 'Apply a second coat of joint compound, feathering further out. Once dry, sand smooth with 120-grit then 220-grit sandpaper.', t: '50 min', photo: true, tip: 'Use a bright work light held at an angle to reveal imperfections before painting. Fill any low spots with a thin skim coat.' },
      { s: 'Prime the patched area with a stain-blocking primer, then apply two coats of matching paint.', t: '20 min', photo: true, tip: 'Always prime bare drywall mud — it absorbs paint differently than the surrounding wall. Feather the paint 6+ inches past the patch.' },
    ],
    shop: [
      { n: 'Drywall Repair Patch Kit', sz: '6" x 6"', pr: 899, store: 'Home Depot', sku: '1001384562', stock: 'In Stock', tag: 'essential' },
      { n: 'DAP DryDex Joint Compound', sz: '32 oz', pr: 1198, store: 'Home Depot', sku: '1000548921', stock: 'In Stock', tag: 'essential' },
      { n: 'FibaTape Self-Adhesive Mesh Tape', sz: '1.875" x 300 ft', pr: 697, store: 'Lowe\'s', sku: '154827', stock: 'In Stock', tag: 'essential' },
      { n: '3M Pro Grade Sandpaper Pack', sz: '120/220 grit, 6 sheets', pr: 598, store: 'Home Depot', sku: '1001251743', stock: 'In Stock', tag: 'essential' },
      { n: 'Zinsser Bulls Eye 1-2-3 Primer', sz: '1 qt', pr: 1298, store: 'Lowe\'s', sku: '209827', stock: 'In Stock', tag: 'essential' },
    ],
    matEst: 3690,
  },

  plumbing: {
    title: 'Fixing a Leaky Faucet',
    conf: 78,
    xp: 50,
    save: 14000,
    why: 'Most faucet leaks are caused by a worn cartridge, O-ring, or washer that costs a few dollars to replace. The repair itself is straightforward once you identify your faucet type. A dripping faucet wastes up to 3,000 gallons per year.',
    flags: [],
    fq: [
      { q: 'What type of faucet is it?', opts: ['Single-handle', 'Double-handle', 'Pull-down/pull-out', 'Not sure'] },
      { q: 'Where is it leaking from?', opts: ['Spout (dripping into sink)', 'Base of the faucet', 'Under the sink', 'Handle area'] },
      { q: 'How old is the faucet?', opts: ['Less than 5 years', '5-10 years', '10-20 years', 'Over 20 years'] },
      { q: 'Can you access the shutoff valves under the sink?', opts: ['Yes, easy access', 'Yes, but tight space', 'No shutoff valves visible', 'Not sure'] },
    ],
    diy: { lo: 1500, hi: 4500, hrs: 2, time: '1-2 hours', risk: 'Low to moderate. Main risk is cross-threading a connection or not fully sealing, which can cause a slow leak. Always test thoroughly before reassembly.' },
    pro: { lo: 15000, hi: 25000, time: '30-60 minutes', risk: 'Minimal — plumbers carry common parts and can diagnose issues quickly.', note: 'Many plumbers charge a flat diagnostic fee ($50-$100) plus parts. If the faucet is very old, replacement may be more cost-effective than repair.', script: 'Hi, I have a leaky [single-handle/double-handle] faucet in my [kitchen/bathroom]. It\'s dripping from the [spout/base/handle]. The faucet is about [age] years old. Could you provide an estimate for repair? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Shut off water & prep', time: '10 min' },
      { phase: 'Remove handle & trim', time: '15 min' },
      { phase: 'Remove & inspect cartridge', time: '15 min' },
      { phase: 'Replace cartridge/washer', time: '15 min' },
      { phase: 'Reassemble faucet', time: '15 min' },
      { phase: 'Test & check for leaks', time: '10 min' },
    ],
    tools: [
      { n: 'Adjustable Wrench', e: '\u{1F527}', r: 'Required', tip: 'Use a cloth or tape on the wrench jaws to avoid scratching chrome fixtures.' },
      { n: 'Basin Wrench', e: '\u{1F527}', r: 'Recommended', tip: 'Essential if you need to access mounting nuts under the sink in tight spaces.' },
      { n: 'Tongue-and-Groove Pliers', e: '\u{1F527}', r: 'Required', tip: 'Channel-lock style pliers provide the grip needed to remove cartridge retaining nuts.' },
      { n: 'Screwdriver Set', e: '\u{1FA9B}', r: 'Required', tip: 'You\'ll need both Phillips and flat-head. Many handles use a small Allen screw under a decorative cap.' },
      { n: 'Allen Key Set', e: '\u{1F527}', r: 'Required', tip: 'Most single-handle faucets use a 1/8" or 3/32" Allen screw to hold the handle. Bring the full set.' },
    ],
    steps: [
      { s: 'Turn off the hot and cold water shutoff valves under the sink. Open the faucet to release remaining water pressure and confirm the water is off.', t: '5 min', photo: false, tip: 'Place a towel in the sink to catch small parts and prevent them from going down the drain.' },
      { s: 'Remove the faucet handle by prying off the decorative cap, then unscrewing the handle screw (usually Phillips or Allen). Pull the handle straight off.', t: '10 min', photo: true, tip: 'Take photos of each step so you know exactly how to reassemble. Some handles need a gentle wiggle or a handle puller if stuck.' },
      { s: 'Remove the cartridge retaining nut or clip. Pull the cartridge straight out, noting its orientation. Inspect the cartridge and O-rings for wear.', t: '15 min', photo: true, tip: 'Take the old cartridge to the hardware store to find an exact match. Note the faucet brand and model if possible.' },
      { s: 'Install the new cartridge or replacement O-rings/washers. Apply a thin coat of plumber\'s grease to all O-rings before installation.', t: '10 min', photo: true, tip: 'Make sure the cartridge is oriented the same way as the original. The hot/cold tabs should match their original position.' },
      { s: 'Reassemble the faucet in reverse order: retaining nut/clip, handle, decorative cap. Hand-tighten first, then snug with tools — don\'t overtighten.', t: '10 min', photo: false, tip: 'Overtightening is the number one cause of cracked trim and stripped threads. Snug is enough.' },
      { s: 'Slowly turn on the shutoff valves. Test both hot and cold. Check under the sink for any drips after 5 minutes of use.', t: '10 min', photo: true, tip: 'Open the faucet before turning on the supply valves to prevent pressure spikes. Run the water for a full minute to flush any debris.' },
    ],
    shop: [
      { n: 'Danco Faucet Repair Kit (Universal)', sz: 'Multi-pack', pr: 1298, store: 'Home Depot', sku: '1001392748', stock: 'In Stock', tag: 'essential' },
      { n: 'Plumber\'s Silicone Grease', sz: '1 oz tube', pr: 498, store: 'Home Depot', sku: '1001256839', stock: 'In Stock', tag: 'essential' },
      { n: 'PTFE Teflon Tape', sz: '1/2" x 260"', pr: 198, store: 'Lowe\'s', sku: '271946', stock: 'In Stock', tag: 'essential' },
      { n: 'O-Ring Assortment Kit', sz: '200-piece', pr: 798, store: 'Lowe\'s', sku: '305284', stock: 'In Stock', tag: 'recommended' },
      { n: 'Moen 1225 Replacement Cartridge', sz: 'Standard', pr: 2498, store: 'Home Depot', sku: '1000042385', stock: 'In Stock', tag: 'if-needed' },
    ],
    matEst: 2794,
  },

  painting: {
    title: 'Painting a Room',
    conf: 92,
    xp: 50,
    save: 40000,
    why: 'Interior painting is the highest-confidence DIY project. With good prep, even a first-timer can achieve excellent results. The labor savings are substantial since painting is mostly time rather than skill, and the materials are inexpensive relative to professional quotes.',
    flags: [],
    fq: [
      { q: 'What size is the room?', opts: ['Small (bathroom/closet, < 80 sq ft)', 'Medium (bedroom, 100-150 sq ft)', 'Large (living room, 150-250 sq ft)', 'Extra large (> 250 sq ft or multiple rooms)'] },
      { q: 'What condition are the walls in?', opts: ['Good — smooth, no repairs needed', 'Fair — small nail holes, minor scuffs', 'Rough — cracks, peeling, or water damage', 'New drywall / never painted'] },
      { q: 'What kind of color change?', opts: ['Same or similar color refresh', 'Light to light color', 'Light to dark color', 'Dark to light color (needs extra primer)'] },
      { q: 'Are you including trim and ceiling?', opts: ['Walls only', 'Walls and ceiling', 'Walls and trim', 'Walls, ceiling, and trim'] },
    ],
    diy: { lo: 8000, hi: 20000, hrs: 8, time: '6-10 hours (1-2 days)', risk: 'Very low. Painting mistakes are easily fixable with another coat. The main risk is drips on flooring, which drop cloths prevent.' },
    pro: { lo: 40000, hi: 80000, time: '4-6 hours', risk: 'Minimal — professional painters deliver consistent, fast results.', note: 'Professional pricing is typically $2-$4 per square foot of wall area, or $300-$600+ per room. Includes labor, paint, and prep.', script: 'Hi, I\'d like to get an estimate for painting a [size] room — about [dimensions]. The walls are in [good/fair/rough] condition. I\'m looking at [walls only / walls and trim / etc.]. Could you provide a quote? I\'m comparing estimates from a few painters.' },
    tl: [
      { phase: 'Move furniture & lay drop cloths', time: '30 min' },
      { phase: 'Patch holes & sand walls', time: '30 min' },
      { phase: 'Tape trim, windows & edges', time: '30 min' },
      { phase: 'Apply primer (if needed)', time: '45 min' },
      { phase: 'Cut in edges with brush', time: '45 min' },
      { phase: 'Roll walls — first coat', time: '45 min' },
      { phase: 'Dry time between coats', time: '2 hrs' },
      { phase: 'Roll walls — second coat', time: '45 min' },
      { phase: 'Remove tape & clean up', time: '30 min' },
    ],
    tools: [
      { n: 'Roller Frame (9")', e: '\u{1F3A8}', r: 'Required', tip: 'A quality roller frame with a comfortable grip makes a huge difference. Look for one with a threaded end for an extension pole.' },
      { n: 'Paint Tray', e: '\u{1F3A8}', r: 'Required', tip: 'Use a sturdy metal tray rather than disposable plastic — it won\'t flex when you load the roller. Add a liner for easy cleanup.' },
      { n: 'Angled Sash Brush (2.5")', e: '\u{1F3A8}', r: 'Required', tip: 'A quality angled brush is the single most important painting tool. Spend $10-15 on a Purdy or Wooster for crisp cut lines.' },
      { n: 'Painter\'s Tape (1.5")', e: '\u{1F3A8}', r: 'Required', tip: 'Apply tape to completely dry surfaces and press edges firmly. Remove at a 45-degree angle while the last coat is still slightly tacky.' },
      { n: 'Drop Cloths', e: '\u{1F3A8}', r: 'Required', tip: 'Canvas drop cloths stay in place better than plastic. Use plastic over furniture and canvas on floors.' },
      { n: 'Extension Pole (4-8 ft)', e: '\u{1F3A8}', r: 'Recommended', tip: 'Paint the entire wall from floor to ceiling without bending or using a ladder. Saves your back and produces more even coverage.' },
    ],
    steps: [
      { s: 'Move furniture to the center of the room and cover with plastic sheeting. Lay canvas drop cloths on the floor along all walls. Remove outlet covers and light switch plates.', t: '30 min', photo: false, tip: 'Put all outlet cover screws in a labeled zip-lock bag so you don\'t lose them. A quick vacuum along baseboards removes dust that would stick to wet paint.' },
      { s: 'Apply painter\'s tape along all trim, door frames, window frames, and ceiling edges. Press tape edges firmly with a putty knife for clean lines.', t: '30 min', photo: false, tip: 'The key to sharp lines is sealing the tape edge. Run a putty knife or credit card along the tape where it meets the wall to prevent paint bleed.' },
      { s: 'Apply primer to any patched areas, bare drywall, or dark surfaces. Allow primer to dry completely per label instructions.', t: '45 min', photo: false, tip: 'Spot-priming patches prevents them from showing through the topcoat. If changing from dark to light, prime the entire wall.' },
      { s: 'Cut in all edges with your angled brush — ceiling line, corners, around trim, outlets, and any areas the roller can\'t reach. Work in 3-foot sections.', t: '45 min', photo: false, tip: 'Load the brush about 1/3 of the way up the bristles and tap off excess. Maintain a wet edge to avoid lap marks. Work from top to bottom.' },
      { s: 'Load the roller evenly in the tray and roll walls in a "W" pattern, then fill in with even, overlapping strokes. Work from ceiling to floor in 3-foot sections.', t: '45 min', photo: true, tip: 'Don\'t press too hard — let the roller do the work. Reload frequently and maintain a wet edge. Roll slowly to avoid spattering.' },
      { s: 'Allow the first coat to dry for 2-4 hours. Apply a second coat using the same cut-in and rolling technique for full, even coverage.', t: '3 hrs', photo: true, tip: 'The second coat goes faster because you already have clean cut lines as a guide. Check for holidays (thin spots) with a bright light before the paint dries.' },
      { s: 'Remove painter\'s tape at a 45-degree angle while the final coat is still slightly tacky. Replace outlet covers. Move furniture back and clean up.', t: '30 min', photo: true, tip: 'If the paint has fully dried on the tape, score along the tape edge with a utility knife first to prevent peeling. Clean brushes in warm soapy water immediately.' },
    ],
    shop: [
      { n: 'Behr Premium Plus Interior Paint', sz: '2 gallons', pr: 7896, store: 'Home Depot', sku: '1001850274', stock: 'In Stock', tag: 'essential' },
      { n: 'Zinsser Bulls Eye 1-2-3 Primer', sz: '1 gallon', pr: 2498, store: 'Home Depot', sku: '1001384510', stock: 'In Stock', tag: 'essential' },
      { n: 'ScotchBlue Original Painter\'s Tape', sz: '1.88" x 60 yd, 2-pack', pr: 1297, store: 'Lowe\'s', sku: '193847', stock: 'In Stock', tag: 'essential' },
      { n: 'Wooster Pro Roller Covers', sz: '9" x 3/8" nap, 3-pack', pr: 1199, store: 'Home Depot', sku: '1001262843', stock: 'In Stock', tag: 'essential' },
      { n: 'HDX Canvas Drop Cloth', sz: '9 ft x 12 ft', pr: 1697, store: 'Home Depot', sku: '1001547832', stock: 'In Stock', tag: 'essential' },
      { n: 'Linzer Paint Tray Liner', sz: '9", 5-pack', pr: 498, store: 'Lowe\'s', sku: '246913', stock: 'In Stock', tag: 'recommended' },
    ],
    matEst: 15085,
  },

  lawn: {
    title: 'Lawn Renovation & Overseeding',
    conf: 88,
    xp: 50,
    save: 25000,
    why: 'Lawn renovation is a highly rewarding DIY project with visible results within 2-3 weeks. The process is methodical and forgiving — seed is inexpensive, so you can always overseed again if coverage is thin. Professional lawn services charge premium rates for work that is mostly labor.',
    flags: [],
    fq: [
      { q: 'How large is the lawn area?', opts: ['Small (under 2,000 sq ft)', 'Medium (2,000-5,000 sq ft)', 'Large (5,000-10,000 sq ft)', 'Extra large (over 10,000 sq ft)'] },
      { q: 'What is the current condition?', opts: ['Mostly healthy, just thin patches', 'About 50/50 grass and bare spots', 'Mostly bare or dead grass', 'Starting from scratch / new construction'] },
      { q: 'What grass type do you want?', opts: ['Cool-season (fescue, bluegrass, rye)', 'Warm-season (Bermuda, zoysia, St. Augustine)', 'Not sure — need recommendation', 'Matching existing grass'] },
      { q: 'How much sun does the area get?', opts: ['Full sun (6+ hours)', 'Partial sun (3-6 hours)', 'Mostly shade (< 3 hours)', 'Mixed — some sunny, some shady areas'] },
    ],
    diy: { lo: 5000, hi: 15000, hrs: 5, time: '4-6 hours (plus daily watering for 2-3 weeks)', risk: 'Low. The main risks are seeding at the wrong time of year or not watering enough during germination. Both are easily avoided with planning.' },
    pro: { lo: 30000, hi: 60000, time: '2-4 hours', risk: 'Minimal — professionals have commercial aerators and spreaders for even coverage.', note: 'Professional lawn renovation typically includes aeration, overseeding, and starter fertilizer. Sod installation is significantly more expensive ($1-$2 per sq ft).', script: 'Hi, I\'m looking to renovate my lawn — it\'s about [size] square feet and currently [condition]. I\'d like to get an estimate for aeration, overseeding, and starter fertilizer. Could you come take a look? I\'m getting a few quotes.' },
    tl: [
      { phase: 'Mow existing lawn very short', time: '30 min' },
      { phase: 'Dethatch and rake debris', time: '45 min' },
      { phase: 'Aerate the soil', time: '45 min' },
      { phase: 'Spread seed with spreader', time: '30 min' },
      { phase: 'Apply starter fertilizer', time: '20 min' },
      { phase: 'Initial watering', time: '20 min' },
    ],
    tools: [
      { n: 'Garden Rake', e: '\u{1F33F}', r: 'Required', tip: 'A stiff-tined garden rake works best for dethatching and working seed into the soil. A leaf rake is too flexible.' },
      { n: 'Broadcast Spreader', e: '\u{1F33F}', r: 'Required', tip: 'Calibrate the spreader before starting. Walk at a steady pace and overlap each pass slightly to avoid striping.' },
      { n: 'Garden Hose with Nozzle', e: '\u{1F33F}', r: 'Required', tip: 'Use a gentle shower setting for watering seed — a hard stream will displace seeds. A sprinkler attachment is ideal for daily watering.' },
      { n: 'Lawn Mower', e: '\u{1F33F}', r: 'Required', tip: 'Set the mower to its lowest safe setting (about 1.5-2 inches) for the initial cut. This helps seed make contact with soil.' },
      { n: 'Core Aerator (Rental)', e: '\u{1F33F}', r: 'Recommended', tip: 'Rent a core aerator from Home Depot ($75-$90/day). Make two passes in perpendicular directions for best results.' },
    ],
    steps: [
      { s: 'Mow the existing lawn as short as possible (1.5-2 inches). Bag the clippings to expose bare soil. Remove any leaves or debris.', t: '30 min', photo: true, tip: 'Don\'t scalp the lawn down to dirt — just cut it very short. If the grass is tall, lower the mower height gradually over two mowings.' },
      { s: 'Dethatch the lawn with a garden rake or dethatching rake, pulling up dead grass and debris. Rake until you can see bare soil between grass plants.', t: '45 min', photo: false, tip: 'A thatch layer over 1/2 inch thick prevents seed from reaching soil. For large lawns, consider renting a power dethatcher ($60-$80/day).' },
      { s: 'Aerate the lawn by making two passes with a core aerator in perpendicular directions. Leave the soil plugs on the surface — they\'ll break down naturally.', t: '45 min', photo: true, tip: 'Aerate when the soil is slightly moist (not wet or dry). The tines need to penetrate 2-3 inches. Water the lawn the day before if soil is dry.' },
      { s: 'Load the broadcast spreader with grass seed and apply at the rate recommended on the bag. Make two half-rate passes in perpendicular directions for even coverage.', t: '30 min', photo: false, tip: 'For cool-season lawns, apply 3-4 lbs per 1,000 sq ft. For warm-season, follow the bag rate. Splitting into two passes prevents bare stripes.' },
      { s: 'Apply starter fertilizer with the broadcast spreader at the recommended rate. Starter fertilizer is high in phosphorus, which promotes root development.', t: '20 min', photo: false, tip: 'Don\'t use regular lawn fertilizer — it\'s too high in nitrogen for new seed. Look for a formulation like 10-18-10 or similar starter blend.' },
      { s: 'Water the entire area lightly but thoroughly. Set up a daily watering schedule: 2-3 light waterings per day for the first 2 weeks, then gradually reduce frequency.', t: '20 min', photo: true, tip: 'The goal is to keep the top 1 inch of soil consistently moist without puddling. New seed germinates in 7-21 days depending on grass type. Don\'t mow until grass is 3+ inches tall.' },
    ],
    shop: [
      { n: 'Scotts Turf Builder Grass Seed', sz: '7 lb (covers 2,800 sq ft)', pr: 3498, store: 'Home Depot', sku: '1001843756', stock: 'In Stock', tag: 'essential' },
      { n: 'Scotts Turf Builder Starter Fertilizer', sz: '15 lb (covers 5,000 sq ft)', pr: 2798, store: 'Home Depot', sku: '1001256794', stock: 'In Stock', tag: 'essential' },
      { n: 'Premium Topsoil', sz: '1 cu ft bag', pr: 497, store: 'Lowe\'s', sku: '168453', stock: 'In Stock', tag: 'recommended' },
      { n: 'Gilmour Adjustable Hose Nozzle', sz: 'Standard', pr: 1298, store: 'Lowe\'s', sku: '342581', stock: 'In Stock', tag: 'recommended' },
      { n: 'Scotts Turf Builder Lawn Food', sz: '12.5 lb (5,000 sq ft)', pr: 2997, store: 'Home Depot', sku: '1001537842', stock: 'In Stock', tag: 'optional' },
    ],
    matEst: 8091,
  },

  deck: {
    title: 'Deck Staining & Sealing',
    conf: 85,
    xp: 50,
    save: 45000,
    why: 'Deck staining is labor-intensive but technically simple. Professional quotes are high because of the large surface area and prep time. DIY staining produces results identical to professional work if you prep the surface properly — cleaning and sanding are 80% of the job.',
    flags: [],
    fq: [
      { q: 'What size is the deck?', opts: ['Small (under 150 sq ft)', 'Medium (150-300 sq ft)', 'Large (300-500 sq ft)', 'Extra large (over 500 sq ft)'] },
      { q: 'What type of wood is it?', opts: ['Pressure-treated pine', 'Cedar or redwood', 'Composite (Trex, TimberTech)', 'Hardwood (ipe, mahogany)', 'Not sure'] },
      { q: 'What is the current condition?', opts: ['Bare / new wood, never stained', 'Previous stain is worn but intact', 'Stain is peeling or flaking', 'Wood is gray or weathered'] },
      { q: 'Has the deck been stained or sealed before?', opts: ['No — bare or new wood', 'Yes — semi-transparent stain', 'Yes — solid color stain', 'Yes — clear sealer only'] },
    ],
    diy: { lo: 10000, hi: 25000, hrs: 8, time: '6-10 hours over 2 days', risk: 'Low. Staining is forgiving — work with the wood grain and maintain a wet edge. The main risk is applying over improperly prepped wood, which causes peeling.' },
    pro: { lo: 50000, hi: 100000, time: '4-8 hours', risk: 'Minimal — professionals have commercial sprayers and can handle large decks efficiently.', note: 'Professional deck staining typically runs $2-$4 per square foot, including prep, cleaning, and two coats of stain. Stripping old stain adds to the cost.', script: 'Hi, I have a [size] square foot [wood type] deck that needs staining. It\'s currently [condition]. I\'d like to get an estimate for cleaning, prepping, and applying stain. Could you take a look? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Clear deck & sweep', time: '20 min' },
      { phase: 'Clean / pressure wash', time: '60 min' },
      { phase: 'Sand rough spots', time: '45 min' },
      { phase: 'Apply brightener / prep', time: '30 min' },
      { phase: 'Apply first coat of stain', time: '90 min' },
      { phase: 'Dry time', time: '4 hrs' },
      { phase: 'Apply second coat', time: '90 min' },
    ],
    tools: [
      { n: 'Pressure Washer (Rental)', e: '\u{1FAB5}', r: 'Required', tip: 'Use a fan tip (25-40 degree) at 1,500-2,000 PSI for deck cleaning. Too much pressure damages wood grain. Keep the nozzle 6-8 inches from the surface.' },
      { n: 'Orbital Sander', e: '\u{1FAB5}', r: 'Recommended', tip: 'Sand with 80-grit to smooth raised grain after cleaning, then follow with 120-grit. Sand with the grain direction.' },
      { n: 'Stain Pad Applicator', e: '\u{1FAB5}', r: 'Required', tip: 'A pad on a pole lets you stain standing up and produces a smoother finish than a roller. Apply with the grain.' },
      { n: 'Stain Brush (4")', e: '\u{1FAB5}', r: 'Required', tip: 'Use a brush for railings, spindles, and areas between boards where the pad can\'t reach. A natural bristle brush works best for oil-based stain.' },
      { n: 'Paint Roller (9")', e: '\u{1FAB5}', r: 'Recommended', tip: 'A 3/8" nap roller speeds up large flat areas. Back-brush with a pad or brush immediately after rolling to work stain into the grain.' },
      { n: 'Safety Glasses', e: '\u{1FAB5}', r: 'Required', tip: 'Wear safety glasses during pressure washing and sanding. Stain splatter is particularly hard to remove from eyes.' },
    ],
    steps: [
      { s: 'Remove all furniture, planters, and grill from the deck. Sweep thoroughly and remove any debris from between the boards.', t: '20 min', photo: false, tip: 'Use a putty knife or flathead screwdriver to clean debris from between deck boards. This prevents water from getting trapped and causing rot.' },
      { s: 'Clean the deck with a pressure washer or deck cleaner solution. Work with the grain in long, overlapping strokes. Allow to dry for 24-48 hours.', t: '60 min', photo: true, tip: 'If pressure washing, test on an inconspicuous area first. Too much pressure will fuzz the wood grain. A deck cleaner with oxalic acid works well for gray or stained wood.' },
      { s: 'Sand any rough spots, raised grain, or splintered areas with 80-grit sandpaper, then follow with 120-grit for a smooth surface.', t: '45 min', photo: false, tip: 'Don\'t sand the entire deck unless necessary — focus on areas that are rough to the touch. Always sand with the grain direction.' },
      { s: 'Apply deck brightener per product instructions to neutralize the cleaner and restore the wood\'s natural pH. Rinse thoroughly and allow to dry.', t: '30 min', photo: false, tip: 'Deck brightener (oxalic acid based) opens the wood pores for better stain penetration. This step is often skipped but makes a significant difference in stain adhesion.' },
      { s: 'Apply the first coat of deck stain using a pad applicator, working with the grain. Do 2-3 boards at a time to maintain a wet edge. Use a brush for railings and tight spots.', t: '90 min', photo: true, tip: 'Start with railings and spindles, then do the floor boards working toward your exit. Apply thin, even coats — heavy application causes tacky spots and peeling.' },
      { s: 'Allow the first coat to dry for 4-6 hours (or per product label). Apply a second coat using the same technique for maximum protection and color depth.', t: '90 min', photo: true, tip: 'The second coat can be applied more quickly since you\'re working over a sealed surface. Check the weather — you need 24 hours of dry weather after the final coat.' },
      { s: 'Allow the stain to cure for 24-48 hours before replacing furniture. Clean tools and applicators with the appropriate solvent (mineral spirits for oil-based, water for water-based).', t: '15 min', photo: false, tip: 'Don\'t walk on the stain for at least 24 hours. Avoid dragging furniture — use felt pads under all legs to prevent scratching the new finish.' },
    ],
    shop: [
      { n: 'Behr Premium Deck Cleaner', sz: '1 gallon', pr: 1698, store: 'Home Depot', sku: '1001845236', stock: 'In Stock', tag: 'essential' },
      { n: 'Behr Premium Semi-Transparent Deck Stain', sz: '2 gallons', pr: 7998, store: 'Home Depot', sku: '1001845381', stock: 'In Stock', tag: 'essential' },
      { n: 'Stain Applicator Pad with Pole', sz: '10" pad', pr: 1497, store: 'Lowe\'s', sku: '287361', stock: 'In Stock', tag: 'essential' },
      { n: '3M Sandpaper Assortment', sz: '80/120/220 grit, 9 sheets', pr: 898, store: 'Home Depot', sku: '1001294735', stock: 'In Stock', tag: 'essential' },
      { n: 'FrogTape Multi-Surface Painter\'s Tape', sz: '1.41" x 60 yd', pr: 798, store: 'Lowe\'s', sku: '415283', stock: 'In Stock', tag: 'recommended' },
      { n: 'Olympic Deck Brightener', sz: '2.5 gallon', pr: 1998, store: 'Lowe\'s', sku: '356284', stock: 'In Stock', tag: 'recommended' },
    ],
    matEst: 14887,
  },

  electric: {
    title: 'Replacing an Outlet or Switch',
    conf: 65,
    xp: 50,
    save: 10000,
    why: 'Swapping a standard outlet or light switch is a common DIY task that saves significantly on electrician service call fees. The parts cost under $5, while an electrician typically charges $100-$200 for this simple swap. However, electrical work demands strict safety protocol.',
    flags: [
      '\u26A0\uFE0F Turn off breaker before starting — verify power is off with a voltage tester',
      '\u26A0\uFE0F Local codes may require permits for electrical work — check your municipality',
    ],
    fq: [
      { q: 'What type of outlet or switch?', opts: ['Standard outlet (15A)', 'GFCI outlet (bathroom/kitchen)', 'Light switch (single pole)', 'Light switch (3-way)', 'Dimmer switch'] },
      { q: 'How old is the home\'s wiring?', opts: ['Modern (copper, grounded)', 'Older (copper, may be ungrounded)', 'Aluminum wiring', 'Not sure'] },
      { q: 'Can you access the breaker panel easily?', opts: ['Yes — clearly labeled', 'Yes — but labels are wrong or missing', 'Panel is hard to access', 'I have a fuse box, not breakers'] },
      { q: 'How many outlets/switches need replacing?', opts: ['Just 1', '2-3', '4-6', 'More than 6'] },
    ],
    diy: { lo: 1000, hi: 3000, hrs: 1, time: '30-60 minutes per outlet', risk: 'Moderate. Electrical shock risk is real if the circuit is not properly de-energized. Always verify with a voltage tester before touching any wires.' },
    pro: { lo: 10000, hi: 20000, time: '15-30 minutes', risk: 'Minimal — licensed electricians handle code compliance and testing.', note: 'Most electricians charge a minimum service call fee ($75-$150) plus per-outlet pricing ($5-$15 each). Doing multiple outlets at once reduces the per-unit cost significantly.', script: 'Hi, I need to replace [number] [outlets/switches] in my home. They\'re standard [15-amp outlets / single-pole switches / GFCI outlets]. My home was built in [year] with [copper/not sure] wiring. Could you provide an estimate? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Turn off breaker & verify', time: '5 min' },
      { phase: 'Test with voltage tester', time: '5 min' },
      { phase: 'Remove cover plate & old device', time: '10 min' },
      { phase: 'Connect wires to new device', time: '15 min' },
      { phase: 'Install & test', time: '10 min' },
    ],
    tools: [
      { n: 'Non-Contact Voltage Tester', e: '\u26A1', r: 'Required', tip: 'ALWAYS test before touching any wire. Test on a known live circuit first to verify the tester is working properly.' },
      { n: 'Screwdriver Set (insulated)', e: '\u26A1', r: 'Required', tip: 'Use insulated screwdrivers rated for electrical work. Both Phillips and flat-head are needed for terminal screws and cover plates.' },
      { n: 'Wire Strippers', e: '\u26A1', r: 'Recommended', tip: 'Match the stripper gauge to your wire size (14 AWG for 15A circuits, 12 AWG for 20A). Strip about 3/4 inch of insulation for terminal connections.' },
      { n: 'Needle-Nose Pliers', e: '\u26A1', r: 'Required', tip: 'Use to bend wire hooks for terminal screws. Wrap wire clockwise around the screw so it tightens as you drive the screw.' },
      { n: 'Flashlight / Headlamp', e: '\u26A1', r: 'Recommended', tip: 'You\'ll be working with the power off — a headlamp keeps both hands free. Check wire colors inside the box carefully.' },
    ],
    steps: [
      { s: 'Turn off the circuit breaker for the outlet/switch you are replacing. Use a non-contact voltage tester to verify power is completely off at the device.', t: '5 min', photo: false, tip: 'Never trust a breaker label alone. ALWAYS test with a voltage tester. Test both the hot (black) and neutral (white) wires. If in doubt, turn off the main breaker.' },
      { s: 'Remove the cover plate and unscrew the outlet/switch from the electrical box. Carefully pull the device out, keeping wires attached. Note which wire connects where.', t: '10 min', photo: true, tip: 'Take a photo of the wiring before disconnecting anything. Note: black = hot, white = neutral, green/bare = ground. For 3-way switches, also note the common (different colored screw) terminal.' },
      { s: 'Disconnect the wires from the old device. For screw terminals, loosen the screws. For push-in (backstab) connections, insert a small screwdriver into the release slot.', t: '5 min', photo: true, tip: 'Push-in connections are less reliable than screw terminals. When installing the new device, use the screw terminals for a more secure connection.' },
      { s: 'Connect the wires to the new outlet/switch: black (hot) to brass screw, white (neutral) to silver screw, green/bare (ground) to green screw. Wrap wire clockwise around screws.', t: '10 min', photo: true, tip: 'Ensure all connections are tight with no exposed copper. The wire hook should wrap clockwise around the terminal screw. For GFCI outlets, follow the LINE and LOAD labels carefully.' },
      { s: 'Carefully fold wires back into the box, screw the device in place, and install the cover plate. Turn the breaker back on and test the outlet/switch.', t: '10 min', photo: true, tip: 'For outlets, plug in a lamp or outlet tester to verify proper wiring. For GFCI outlets, press the TEST button — the outlet should click off, then press RESET to restore power.' },
    ],
    shop: [
      { n: 'Leviton Decora Outlet (15A)', sz: '3-pack', pr: 897, store: 'Home Depot', sku: '1001395218', stock: 'In Stock', tag: 'essential' },
      { n: 'Leviton Decora Wall Plate', sz: '1-gang, 5-pack', pr: 698, store: 'Home Depot', sku: '1001293764', stock: 'In Stock', tag: 'essential' },
      { n: 'Ideal Wire Nut Assortment', sz: '100-pack', pr: 498, store: 'Lowe\'s', sku: '382941', stock: 'In Stock', tag: 'essential' },
      { n: 'Commercial Electric Electrical Tape', sz: '3/4" x 60 ft, 3-pack', pr: 397, store: 'Home Depot', sku: '1001247583', stock: 'In Stock', tag: 'essential' },
    ],
    matEst: 2490,
  },

  hvac: {
    title: 'Replacing Air Filter & Thermostat',
    conf: 75,
    xp: 50,
    save: 15000,
    why: 'Filter replacement is a 5-minute job that dramatically improves air quality and system efficiency. Thermostat upgrades are only slightly more involved — most smart thermostats come with clear instructions and labeled wiring. Both tasks have an excellent savings-to-effort ratio.',
    flags: [],
    fq: [
      { q: 'What type of HVAC system do you have?', opts: ['Central AC with furnace', 'Heat pump', 'Mini-split / ductless', 'Window units', 'Not sure'] },
      { q: 'What type of thermostat do you currently have?', opts: ['Basic / manual dial', 'Programmable digital', 'Smart / WiFi enabled', 'Not sure'] },
      { q: 'What size is your current air filter?', opts: ['16x20x1', '16x25x1', '20x20x1', '20x25x1', 'Other / not sure'] },
      { q: 'Do you want WiFi/smart thermostat capability?', opts: ['Yes — I want app control and scheduling', 'No — just a basic programmable thermostat', 'Not sure yet', 'I just need the filter changed'] },
    ],
    diy: { lo: 3000, hi: 8000, hrs: 2, time: '1-2 hours', risk: 'Low. Filter replacement is virtually risk-free. Thermostat wiring is low-voltage (24V), so shock risk is negligible. Main risk is mislabeling wires during thermostat swap.' },
    pro: { lo: 15000, hi: 35000, time: '30-60 minutes', risk: 'Minimal — HVAC technicians verify system operation and can diagnose other issues during the visit.', note: 'HVAC service calls typically start at $75-$150 just for the visit. Thermostat installation is often $100-$200 labor on top of the device cost. Filter replacement is usually included in a maintenance visit.', script: 'Hi, I\'d like to get an estimate for installing a new thermostat and performing a filter change on my [system type]. My current thermostat is a [type]. I\'m also interested in having the system inspected. Could you provide a quote? I\'m comparing a few estimates.' },
    tl: [
      { phase: 'Locate filter & remove old one', time: '5 min' },
      { phase: 'Install new filter', time: '5 min' },
      { phase: 'Turn off HVAC system', time: '5 min' },
      { phase: 'Remove old thermostat', time: '15 min' },
      { phase: 'Wire new thermostat', time: '20 min' },
      { phase: 'Configure & test', time: '15 min' },
    ],
    tools: [
      { n: 'Screwdriver Set', e: '\u2744\uFE0F', r: 'Required', tip: 'Both Phillips and flat-head needed for thermostat mounting and cover plate removal.' },
      { n: 'Drill/Driver', e: '\u2744\uFE0F', r: 'Recommended', tip: 'Needed if your new thermostat has a different mounting plate that requires new wall anchors.' },
      { n: 'Torpedo Level', e: '\u2744\uFE0F', r: 'Recommended', tip: 'A level thermostat looks professional and some models require it for proper operation of mercury-free tilt sensors.' },
      { n: 'Wire Strippers', e: '\u2744\uFE0F', r: 'Recommended', tip: 'If you need to trim or strip thermostat wires, use a wire stripper set for small gauge wire (18-22 AWG).' },
      { n: 'Smartphone', e: '\u2744\uFE0F', r: 'Required for smart thermostat', tip: 'Smart thermostats require the manufacturer app for WiFi setup and configuration. Download the app before you start.' },
    ],
    steps: [
      { s: 'Locate your HVAC filter slot — typically on the return air duct near the furnace or air handler, or behind a vent grille. Slide out the old filter and note the size printed on the frame.', t: '5 min', photo: true, tip: 'The arrow on the filter should point toward the furnace/air handler (in the direction of airflow). Take a photo of the old filter orientation before removing.' },
      { s: 'Insert the new filter with the airflow arrow pointing toward the blower/furnace. Ensure it sits flat and snug in the slot with no gaps around the edges.', t: '5 min', photo: true, tip: 'MERV 8-11 filters offer a good balance of filtration and airflow. Higher MERV ratings can restrict airflow in older systems. Write the install date on the filter frame.' },
      { s: 'Turn off the HVAC system at the thermostat, then flip the breaker for the HVAC system. Remove the old thermostat face plate to expose the wiring.', t: '10 min', photo: true, tip: 'Take a clear photo of the wire connections before removing anything. Label each wire with masking tape — note the letter terminal each wire connects to (R, W, Y, G, C, etc.).' },
      { s: 'Label each wire, disconnect from the old thermostat, and remove the old mounting plate. Tape the wires to the wall to prevent them from falling into the wall cavity.', t: '10 min', photo: true, tip: 'Wrap wires around a pencil pushed through the wall hole to prevent them from falling in. If the old thermostat has a mercury bulb, dispose of it at a hazardous waste facility.' },
      { s: 'Mount the new thermostat base plate to the wall. Connect each labeled wire to the matching terminal on the new thermostat (R to R, W to W, Y to Y, G to G, C to C).', t: '20 min', photo: true, tip: 'If your new thermostat needs a C-wire and you don\'t have one, many smart thermostats include a C-wire adapter. Follow the manufacturer\'s specific instructions for your model.' },
      { s: 'Attach the thermostat face to the base plate, turn the HVAC breaker back on, and follow the on-screen setup. For smart thermostats, connect to WiFi and configure the schedule.', t: '15 min', photo: false, tip: 'Test both heating and cooling modes to verify proper operation. Run each mode for at least 5 minutes. If the system doesn\'t respond, double-check wire connections match the labeled terminals.' },
    ],
    shop: [
      { n: 'Filtrete HVAC Air Filter (MERV 11)', sz: '20x25x1 (check your size)', pr: 2497, store: 'Home Depot', sku: '1001293847', stock: 'In Stock', tag: 'essential' },
      { n: 'Honeywell Home T6 Programmable Thermostat', sz: 'Standard', pr: 4999, store: 'Lowe\'s', sku: '489362', stock: 'In Stock', tag: 'essential' },
      { n: 'Energizer AA Batteries', sz: '4-pack', pr: 598, store: 'Home Depot', sku: '1001576824', stock: 'In Stock', tag: 'essential' },
      { n: 'Wire Label Stickers', sz: '120-count', pr: 699, store: 'Home Depot', sku: '1001683927', stock: 'In Stock', tag: 'recommended' },
      { n: 'TOGGLER Wall Anchors', sz: '#8, 10-pack', pr: 498, store: 'Lowe\'s', sku: '526714', stock: 'In Stock', tag: 'if-needed' },
    ],
    matEst: 7793,
  },

  tile: {
    title: 'Regrouting Tile',
    conf: 80,
    xp: 50,
    save: 20000,
    why: 'Regrouting is tedious but entirely doable as a DIY project. The technique is simple — remove old grout, apply new grout, wipe clean. The savings come from avoiding the labor-intensive billing that contractors charge for this detail-oriented work.',
    flags: [],
    fq: [
      { q: 'What area needs regrouting?', opts: ['Shower walls', 'Shower floor', 'Bathroom floor', 'Kitchen backsplash', 'Kitchen/entry floor'] },
      { q: 'What type of tile is it?', opts: ['Ceramic', 'Porcelain', 'Natural stone (marble, travertine)', 'Glass mosaic', 'Not sure'] },
      { q: 'How would you describe the grout condition?', opts: ['Discolored but intact', 'Cracking in spots', 'Crumbling or missing chunks', 'Moldy or mildewed'] },
      { q: 'How large is the area to regrout?', opts: ['Small (< 20 sq ft)', 'Medium (20-50 sq ft)', 'Large (50-100 sq ft)', 'Extra large (> 100 sq ft)'] },
    ],
    diy: { lo: 2000, hi: 6000, hrs: 4, time: '3-5 hours', risk: 'Low. Regrouting is forgiving — excess grout wipes off tile easily. The main challenge is removing old grout without damaging the tile edges. Take your time during removal.' },
    pro: { lo: 20000, hi: 40000, time: '3-6 hours', risk: 'Minimal — tile professionals have oscillating tools that speed up grout removal dramatically.', note: 'Tile contractors typically charge $6-$15 per square foot for regrouting, which includes removal, cleaning, application, and sealing. Shower work is at the higher end of the range.', script: 'Hi, I need to have the grout replaced in my [shower/bathroom floor/backsplash]. It\'s about [size] square feet of [ceramic/porcelain/stone] tile. The current grout is [condition]. Could you provide an estimate? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Remove old grout', time: '90 min' },
      { phase: 'Clean joints & vacuum debris', time: '20 min' },
      { phase: 'Mix new grout', time: '10 min' },
      { phase: 'Apply grout with float', time: '45 min' },
      { phase: 'Initial wipe & shape joints', time: '20 min' },
      { phase: 'Final cleaning & haze removal', time: '30 min' },
    ],
    tools: [
      { n: 'Grout Float', e: '\u{1F532}', r: 'Required', tip: 'Hold the float at a 45-degree angle and push grout diagonally across the joints. This packs grout in without pulling it out.' },
      { n: 'Grout Removal Tool', e: '\u{1F532}', r: 'Required', tip: 'A manual grout saw works for small areas. For larger jobs, an oscillating multi-tool with a grout blade is much faster and easier on your hands.' },
      { n: 'Grout Sponge', e: '\u{1F532}', r: 'Required', tip: 'Use a large, dense grout sponge — not a regular kitchen sponge. Wring it almost dry and wipe diagonally across joints in one smooth pass.' },
      { n: 'Bucket (5 gallon)', e: '\u{1F532}', r: 'Required', tip: 'Fill with clean water for sponge rinsing. Change the water frequently — dirty water leaves haze on tiles. Two buckets is ideal.' },
      { n: 'Knee Pads', e: '\u{1F532}', r: 'Recommended', tip: 'You\'ll be on your knees for hours during floor regrouting. Good knee pads prevent soreness and let you work longer comfortably.' },
    ],
    steps: [
      { s: 'Remove old grout using a grout saw or oscillating tool. Work carefully along each joint, removing grout to a depth of at least 2/3 the tile thickness. Avoid scratching tile edges.', t: '90 min', photo: true, tip: 'Don\'t try to remove every last bit of old grout — removing 2/3 of the depth provides enough surface for new grout to bond. Work in small sections to avoid fatigue.' },
      { s: 'Vacuum all loose grout debris from the joints. Wipe down tile surfaces with a damp cloth. For shower areas, apply a mildew-killing cleaner and scrub joints with a brush.', t: '20 min', photo: false, tip: 'A shop vac with a crevice attachment works best. Clean joints are critical for grout adhesion. Let everything dry completely before applying new grout.' },
      { s: 'Mix grout according to package directions to a peanut butter consistency. Let it slake (rest) for 5-10 minutes, then remix briefly. Only mix what you can use in 30 minutes.', t: '10 min', photo: false, tip: 'Grout that\'s too wet will shrink and crack. Too dry and it won\'t pack properly. For shower areas, use a grout with built-in mildew resistance.' },
      { s: 'Apply grout with a float held at 45 degrees, pushing diagonally across the joints. Pack grout firmly into all joints, working in 3-4 square foot sections at a time.', t: '45 min', photo: true, tip: 'Work diagonally to the joint lines — this forces grout in rather than pulling it out. Don\'t skip pressing grout firmly into every joint. Air pockets lead to crumbling grout.' },
      { s: 'After 15-20 minutes (when grout becomes hazy), wipe diagonally across joints with a damp grout sponge. Rinse the sponge frequently and use light pressure — don\'t dig grout out of joints.', t: '20 min', photo: true, tip: 'Timing is important — too soon and you pull grout out, too late and the haze becomes very difficult to remove. Start wiping the first section while still grouting later sections.' },
      { s: 'After grout has cured for 24 hours, remove any remaining haze with a grout haze remover or white vinegar solution. Once fully cured (72 hours), apply grout sealer.', t: '30 min', photo: true, tip: 'Grout sealer is essential for shower areas and floors — it prevents moisture penetration and staining. Reapply sealer annually for best protection.' },
    ],
    shop: [
      { n: 'Polyblend Sanded Grout', sz: '7 lb', pr: 1298, store: 'Home Depot', sku: '1001395271', stock: 'In Stock', tag: 'essential' },
      { n: 'Aqua Mix Grout Sealer', sz: '24 oz', pr: 1498, store: 'Lowe\'s', sku: '285736', stock: 'In Stock', tag: 'essential' },
      { n: 'QEP Grout Removal Tool', sz: 'Standard', pr: 897, store: 'Home Depot', sku: '1001483926', stock: 'In Stock', tag: 'essential' },
      { n: 'Anvil Grout Sponge', sz: 'Large, 3-pack', pr: 598, store: 'Home Depot', sku: '1001284359', stock: 'In Stock', tag: 'essential' },
      { n: 'Aqua Mix Grout Haze Remover', sz: '1 qt', pr: 1098, store: 'Lowe\'s', sku: '413952', stock: 'In Stock', tag: 'recommended' },
    ],
    matEst: 5389,
  },

  appliance: {
    title: 'Cleaning & Fixing a Dishwasher',
    conf: 72,
    xp: 50,
    save: 15000,
    why: 'Many dishwasher problems are caused by clogs, dirty filters, or worn gaskets — not mechanical failure. A thorough cleaning and minor part replacement resolves the majority of issues for under $30 in parts. Appliance repair service calls start at $100+ before any parts.',
    flags: [],
    fq: [
      { q: 'What is the main issue?', opts: ['Not draining properly', 'Not cleaning dishes well', 'Leaking water onto floor', 'Making unusual noise', 'Not starting / error code'] },
      { q: 'How old is the dishwasher?', opts: ['Less than 3 years', '3-7 years', '7-12 years', 'Over 12 years'] },
      { q: 'What brand is it?', opts: ['Bosch', 'KitchenAid / Whirlpool', 'Samsung', 'LG', 'GE', 'Other'] },
      { q: 'Are there any error codes on the display?', opts: ['No error codes', 'Yes — I can see a code', 'No display on my model', 'Not sure how to check'] },
    ],
    diy: { lo: 1500, hi: 5000, hrs: 2, time: '1-2 hours', risk: 'Low. Most dishwasher maintenance involves cleaning accessible parts. The main risk is failing to fix the issue, in which case you call a professional anyway — no harm done.' },
    pro: { lo: 15000, hi: 30000, time: '30-60 minutes', risk: 'Minimal — appliance technicians diagnose issues quickly with experience and diagnostic tools.', note: 'Appliance repair companies charge $80-$150 for a diagnostic visit, which is usually applied toward the repair. Part costs are additional. If the dishwasher is 10+ years old, replacement may be more cost-effective.', script: 'Hi, my [brand] dishwasher is [not draining / leaking / not cleaning well / showing error code]. It\'s about [age] years old, model [number if known]. Could you provide an estimate for diagnosis and repair? I\'m comparing a few options.' },
    tl: [
      { phase: 'Turn off power & water supply', time: '5 min' },
      { phase: 'Clean filter & drain trap', time: '20 min' },
      { phase: 'Inspect & clean spray arms', time: '15 min' },
      { phase: 'Check door gasket', time: '10 min' },
      { phase: 'Run vinegar cleaning cycle', time: '60 min' },
      { phase: 'Test & verify fix', time: '15 min' },
    ],
    tools: [
      { n: 'Screwdriver Set', e: '\u{1F50C}', r: 'Required', tip: 'Needed to remove the kick plate, spray arm caps, and filter covers. Both Phillips and flat-head.' },
      { n: 'Tongue-and-Groove Pliers', e: '\u{1F50C}', r: 'Recommended', tip: 'Useful for loosening hose clamps on the drain line if you need to clear a clog below the filter.' },
      { n: 'Flashlight', e: '\u{1F50C}', r: 'Required', tip: 'Inspect the bottom of the dishwasher tub, drain area, and under the unit for leaks. A headlamp works even better.' },
      { n: 'Wet/Dry Vacuum', e: '\u{1F50C}', r: 'Recommended', tip: 'Invaluable for removing standing water from the bottom of a dishwasher that won\'t drain. Also great for cleaning debris from the filter area.' },
    ],
    steps: [
      { s: 'Turn off the dishwasher and disconnect power (unplug or flip the breaker). Turn off the water supply valve under the sink. Remove the bottom rack for access.', t: '5 min', photo: false, tip: 'Safety first — never work on an appliance with power connected. The water supply valve is usually under the sink, connected to the dishwasher via a braided steel line.' },
      { s: 'Locate and remove the filter assembly (usually at the bottom center). Clean the filter under running water with a soft brush. Remove any food debris, glass, or objects from the sump area.', t: '20 min', photo: true, tip: 'Most modern dishwashers have a twist-and-lift filter. Clean it monthly to prevent drainage issues. If the filter is caked with grease, soak in warm soapy water for 10 minutes.' },
      { s: 'Remove the spray arms by unscrewing the center cap or twisting to unlock. Clear any clogged spray holes with a toothpick or thin wire. Rinse under running water.', t: '15 min', photo: true, tip: 'Hold spray arms up to a light — you should see light through every hole. Calcium buildup can be dissolved by soaking in white vinegar for 30 minutes.' },
      { s: 'Inspect the door gasket (rubber seal) around the door opening. Clean with a damp cloth and mild cleaner. Check for tears, cracks, or hardened sections that could cause leaks.', t: '10 min', photo: true, tip: 'The bottom corners of the gasket are the most common leak points. If the gasket is cracked or doesn\'t spring back when pressed, it needs replacement ($15-$40 for the part).' },
      { s: 'Reassemble all parts. Place a cup of white vinegar upright on the top rack and run a hot water cycle (empty, no detergent). This removes mineral deposits, grease, and odors.', t: '60 min', photo: false, tip: 'For extra cleaning power, sprinkle a cup of baking soda on the bottom of the tub after the vinegar cycle and run a short hot cycle. This deodorizes and brightens the interior.' },
      { s: 'Run a normal cycle with dishes and detergent. Check for proper drainage, cleaning performance, and any leaks around the door and under the unit during the cycle.', t: '15 min', photo: true, tip: 'Place a paper towel under the dishwasher door during the test cycle to detect any small leaks. If the issue persists after cleaning, the problem may require a specific part replacement.' },
    ],
    shop: [
      { n: 'Affresh Dishwasher Cleaner', sz: '6 tablets', pr: 898, store: 'Home Depot', sku: '1001583729', stock: 'In Stock', tag: 'essential' },
      { n: 'Universal Dishwasher Door Gasket', sz: 'Trim-to-fit', pr: 2498, store: 'Lowe\'s', sku: '456283', stock: 'In Stock', tag: 'if-needed' },
      { n: 'Dishwasher Spray Arm (Universal Upper)', sz: 'Standard', pr: 1899, store: 'Home Depot', sku: '1001485237', stock: 'In Stock', tag: 'if-needed' },
      { n: 'Dishwasher Float Switch', sz: 'Universal', pr: 1298, store: 'Lowe\'s', sku: '395182', stock: 'In Stock', tag: 'if-needed' },
      { n: 'Stainless Steel Drain Hose Clamp', sz: '2-pack', pr: 498, store: 'Home Depot', sku: '1001294738', stock: 'In Stock', tag: 'recommended' },
    ],
    matEst: 3894,
  },

  window: {
    title: 'Replacing Window Weatherstripping',
    conf: 90,
    xp: 50,
    save: 8000,
    why: 'Weatherstripping replacement is one of the easiest home improvements with immediate payoff. Drafty windows can increase heating/cooling costs by 10-25%. The materials cost under $20 per window, and the work requires no special skills — just measuring, cutting, and pressing into place.',
    flags: [],
    fq: [
      { q: 'What type of windows do you have?', opts: ['Double-hung (slides up and down)', 'Casement (cranks open)', 'Sliding', 'Fixed / picture window'] },
      { q: 'How many windows need weatherstripping?', opts: ['1-3 windows', '4-8 windows', '9-15 windows', 'Whole house (15+)'] },
      { q: 'How severe are the drafts?', opts: ['Mild — slight draft on windy days', 'Moderate — noticeable cold air', 'Severe — can feel strong drafts', 'Visible gaps / daylight around frame'] },
    ],
    diy: { lo: 1500, hi: 4000, hrs: 2, time: '1-2 hours for 3-5 windows', risk: 'Very low. Weatherstripping is peel-and-stick or press-fit — there\'s nothing to break. If you don\'t like the result, remove and try again.' },
    pro: { lo: 10000, hi: 20000, time: '1-2 hours', risk: 'Minimal — handyman services handle this quickly.', note: 'Most handyman services charge $100-$200 for a service call plus per-window pricing. Since the work is simple, the markup is mostly on the service call fee.', script: 'Hi, I need weatherstripping replaced on [number] windows in my home. They\'re [window type] windows and the current stripping is [worn/missing/damaged]. Could you provide an estimate? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Remove old weatherstripping', time: '15 min' },
      { phase: 'Clean channels & surfaces', time: '15 min' },
      { phase: 'Measure & cut new stripping', time: '15 min' },
      { phase: 'Install new weatherstripping', time: '20 min' },
      { phase: 'Test window closure', time: '10 min' },
    ],
    tools: [
      { n: 'Utility Knife', e: '\u{1FA9F}', r: 'Required', tip: 'Use a sharp blade for clean cuts on weatherstripping material. Replace the blade if it tears instead of cutting cleanly.' },
      { n: 'Tape Measure', e: '\u{1FA9F}', r: 'Required', tip: 'Measure each window individually — they may not all be the same size, even if they look identical.' },
      { n: 'Putty Knife', e: '\u{1FA9F}', r: 'Required', tip: 'A 1.5" putty knife works well for removing old adhesive-backed weatherstripping and cleaning the channel.' },
      { n: 'Scissors', e: '\u{1FA9F}', r: 'Required', tip: 'Heavy-duty scissors cut foam tape and V-strip cleanly. Kitchen shears work well too.' },
    ],
    steps: [
      { s: 'Open the window and carefully remove all old weatherstripping. Peel off adhesive-backed strips. For press-fit types, pull from one end. Note the type and location of each piece.', t: '15 min', photo: true, tip: 'Take the old weatherstripping to the store to match the profile if you\'re unsure what replacement type to buy. Different windows use different profiles.' },
      { s: 'Clean the channels and surfaces where new stripping will be applied. Use a putty knife to remove old adhesive residue, then wipe with rubbing alcohol for a clean bonding surface.', t: '15 min', photo: false, tip: 'Adhesive-backed weatherstripping won\'t stick well to dirty or oily surfaces. A quick wipe with isopropyl alcohol ensures the best bond.' },
      { s: 'Measure the length needed for each window channel. Cut the new weatherstripping to length, adding 1/4 inch extra that can be trimmed for a snug fit.', t: '15 min', photo: false, tip: 'It\'s better to cut slightly long and trim to fit than to cut too short. V-strip (tension seal) is the most durable option for double-hung windows.' },
      { s: 'Install the new weatherstripping: peel backing and press firmly into place for adhesive types, or press into the channel for compression types. Ensure continuous contact with no gaps.', t: '20 min', photo: true, tip: 'Start at one end and work slowly to avoid wrinkles or bubbles. For V-strip, the open end of the V should face the outside to create a seal when the window closes.' },
      { s: 'Close and open the window several times to test. The window should close with slight resistance — snug but not forced. Check for remaining drafts with a candle or incense stick.', t: '10 min', photo: true, tip: 'If the window is too hard to close, the stripping is too thick. If you still feel drafts, check for gaps at corners where strips meet. A lit incense stick makes drafts visible.' },
    ],
    shop: [
      { n: 'Frost King V-Seal Weatherstrip', sz: '17 ft roll, 2-pack', pr: 998, store: 'Home Depot', sku: '1001294853', stock: 'In Stock', tag: 'essential' },
      { n: 'M-D Building Foam Tape', sz: '3/8" x 1/4" x 17 ft, 3-pack', pr: 798, store: 'Lowe\'s', sku: '349271', stock: 'In Stock', tag: 'essential' },
      { n: 'Duck Brand Window Insulation Film Kit', sz: '5 windows', pr: 1498, store: 'Home Depot', sku: '1001385294', stock: 'In Stock', tag: 'recommended' },
      { n: 'Frost King Door Sweep', sz: '36" aluminum/vinyl', pr: 1198, store: 'Lowe\'s', sku: '462935', stock: 'In Stock', tag: 'optional' },
    ],
    matEst: 2494,
  },

  roofing: {
    title: 'Gutter Cleaning & Minor Repair',
    conf: 60,
    xp: 50,
    save: 15000,
    why: 'Gutter cleaning is a straightforward but physically demanding job that professionals charge a premium for. The work is simple — scoop debris, flush with a hose — but the ladder work requires respect for safety. Clogged gutters cause costly water damage, so maintenance is essential.',
    flags: [
      '\u26A0\uFE0F Use proper ladder safety — always have a spotter and maintain 3 points of contact',
      '\u26A0\uFE0F Do not work on wet or icy roof surfaces — wait for dry conditions',
    ],
    fq: [
      { q: 'How many stories is your home?', opts: ['Single story (1 floor)', 'Two story', 'Three story or split-level', 'Not sure of exact gutter height'] },
      { q: 'How many linear feet of gutters?', opts: ['Small home (< 100 ft)', 'Medium home (100-200 ft)', 'Large home (200-300 ft)', 'Very large (300+ ft)'] },
      { q: 'Do you have an extension ladder?', opts: ['Yes — tall enough to reach gutters', 'Yes — but may be too short', 'No — would need to buy or borrow', 'I have scaffolding'] },
      { q: 'How comfortable are you working at height?', opts: ['Very comfortable', 'Somewhat comfortable', 'Nervous but willing', 'Not comfortable — prefer ground-level alternatives'] },
    ],
    diy: { lo: 2000, hi: 6000, hrs: 3, time: '2-4 hours', risk: 'Moderate. The primary risk is falling from a ladder. Use proper ladder safety, work on dry days, and never overreach. Consider hiring a pro for 2+ story homes.' },
    pro: { lo: 15000, hi: 35000, time: '1-3 hours', risk: 'Minimal — professional crews have proper equipment, harnesses, and insurance for working at heights.', note: 'Gutter cleaning typically costs $100-$250 depending on home size and gutter condition. Most companies recommend cleaning twice per year (spring and fall). Some offer annual maintenance plans at a discount.', script: 'Hi, I\'d like to get an estimate for gutter cleaning on my [1-story/2-story] home. It\'s approximately [linear feet] feet of gutters. I\'d also like any minor repairs or reattachment included. Could you provide a quote? I\'m getting a few estimates.' },
    tl: [
      { phase: 'Set up ladder & safety gear', time: '15 min' },
      { phase: 'Scoop debris from gutters', time: '60 min' },
      { phase: 'Flush gutters with hose', time: '30 min' },
      { phase: 'Check & clear downspouts', time: '20 min' },
      { phase: 'Patch holes & reattach loose sections', time: '20 min' },
    ],
    tools: [
      { n: 'Extension Ladder', e: '\u{1F3E0}', r: 'Required', tip: 'The ladder must extend at least 3 feet above the gutter line. Set it at a 75-degree angle (4:1 rule — 1 foot out for every 4 feet up). Use a stabilizer bar to protect gutters.' },
      { n: 'Gutter Scoop', e: '\u{1F3E0}', r: 'Required', tip: 'A plastic gutter scoop fits the gutter profile and won\'t scratch the finish. In a pinch, an old kitchen spatula works. Never use metal tools that can dent the gutter.' },
      { n: 'Heavy-Duty Work Gloves', e: '\u{1F3E0}', r: 'Required', tip: 'Gutters can have sharp edges, screws, and decomposing debris. Waterproof gloves with good grip protect your hands and improve ladder grip.' },
      { n: 'Garden Hose with Spray Nozzle', e: '\u{1F3E0}', r: 'Required', tip: 'After scooping, flush gutters toward the downspout with a strong spray. This reveals any leaks in the gutter seams.' },
      { n: 'Safety Glasses', e: '\u{1F3E0}', r: 'Required', tip: 'Debris, dirt, and insects can fall into your eyes when cleaning overhead sections. Wrap-around safety glasses offer the best protection.' },
    ],
    steps: [
      { s: 'Position the extension ladder on firm, level ground. Set the angle at 75 degrees and ensure it extends 3 feet above the gutter line. Have a spotter hold the base. Wear gloves and safety glasses.', t: '15 min', photo: false, tip: 'Never place a ladder on soft ground, slopes, or near power lines. A ladder stabilizer bar ($30) prevents the ladder from damaging gutters and provides a wider, more stable platform.' },
      { s: 'Starting at the downspout end, scoop debris out of the gutter with a gutter scoop or gloved hands. Place debris in a bucket hung from the ladder or drop onto a tarp below.', t: '60 min', photo: true, tip: 'Work away from the downspout so you\'re pushing debris toward it. Move the ladder frequently rather than overreaching — most ladder falls happen from leaning too far to one side.' },
      { s: 'Flush the gutters with a garden hose, starting at the end farthest from the downspout. Watch for proper water flow and note any areas where water pools or leaks through seams.', t: '30 min', photo: true, tip: 'Water should flow steadily toward the downspout with no pooling. If water stands in sections, the gutter may need adjustment (they should slope about 1/4 inch per 10 feet toward the downspout).' },
      { s: 'Check each downspout by running the hose at full pressure into the top. If water backs up, the downspout is clogged. Clear clogs with a plumber\'s snake or by disconnecting the downspout at the bottom.', t: '20 min', photo: false, tip: 'Install downspout strainers ($3 each) to prevent future clogs. Ensure downspout extensions direct water at least 4-6 feet away from the foundation.' },
      { s: 'Patch any small holes with gutter sealant. Reattach loose gutter sections with new gutter screws. Check that all hangers are secure and properly spaced (every 2-3 feet).', t: '20 min', photo: true, tip: 'Gutter sealant works for holes up to 1/4 inch. For larger damage, use a gutter patch kit. Replace rusty screws with stainless steel gutter screws that won\'t corrode.' },
    ],
    shop: [
      { n: 'DAP Gutter & Flashing Sealant', sz: '10.1 oz', pr: 698, store: 'Home Depot', sku: '1001284935', stock: 'In Stock', tag: 'essential' },
      { n: 'Stainless Steel Gutter Screws', sz: '#8 x 1", 50-pack', pr: 898, store: 'Lowe\'s', sku: '435829', stock: 'In Stock', tag: 'essential' },
      { n: 'Amerimax Downspout Strainer', sz: '3-pack', pr: 797, store: 'Home Depot', sku: '1001395827', stock: 'In Stock', tag: 'recommended' },
      { n: 'Amerimax Snap-In Gutter Guard', sz: '3 ft sections, 6-pack', pr: 2498, store: 'Lowe\'s', sku: '513826', stock: 'In Stock', tag: 'recommended' },
      { n: 'Amerimax Gutter Patch Kit', sz: 'Universal', pr: 998, store: 'Home Depot', sku: '1001487253', stock: 'In Stock', tag: 'if-needed' },
    ],
    matEst: 4391,
  },

  concrete: {
    title: 'Patching Concrete Cracks',
    conf: 83,
    xp: 50,
    save: 20000,
    why: 'Concrete crack repair is well within DIY capability for most cracks under 1/2 inch wide. The materials are inexpensive and widely available. Professional concrete work carries high labor costs because of the physical nature of the work and material handling.',
    flags: [],
    fq: [
      { q: 'How wide are the cracks?', opts: ['Hairline (< 1/8 inch)', 'Small (1/8 to 1/4 inch)', 'Medium (1/4 to 1/2 inch)', 'Large (> 1/2 inch) or crumbling'] },
      { q: 'Where is the damaged concrete?', opts: ['Driveway', 'Patio or walkway', 'Garage floor', 'Foundation wall', 'Steps or stoop'] },
      { q: 'Is there a structural concern?', opts: ['No — cosmetic cracks only', 'Maybe — one side is higher than the other', 'Yes — cracks are growing or spreading', 'Not sure — I\'d like guidance'] },
      { q: 'How large is the area to repair?', opts: ['One or two small cracks', 'Several cracks in one area', 'Large area with multiple issues', 'Full slab replacement needed'] },
    ],
    diy: { lo: 2000, hi: 5000, hrs: 3, time: '2-4 hours (plus 24-48 hour cure time)', risk: 'Low for cosmetic repairs. If cracks indicate structural settling or foundation issues, consult a structural engineer before attempting DIY repair.' },
    pro: { lo: 20000, hi: 50000, time: '2-4 hours', risk: 'Minimal — concrete contractors assess structural integrity and use commercial-grade products.', note: 'Professional concrete repair costs $8-$20 per linear foot of crack, or $100-$300 minimum for small jobs. Full slab replacement runs $6-$15 per square foot including removal.', script: 'Hi, I have some concrete cracks on my [driveway/patio/walkway/foundation] that need repair. The cracks are about [width] wide and cover an area of about [size]. Could you take a look and provide an estimate? I\'m comparing a few quotes.' },
    tl: [
      { phase: 'Clean cracks with wire brush', time: '20 min' },
      { phase: 'Widen and prep cracks', time: '30 min' },
      { phase: 'Apply bonding agent', time: '10 min' },
      { phase: 'Fill with patching compound', time: '30 min' },
      { phase: 'Smooth and finish surface', time: '20 min' },
      { phase: 'Cure time (do not walk on)', time: '24-48 hrs' },
    ],
    tools: [
      { n: 'Wire Brush', e: '\u{1F9F1}', r: 'Required', tip: 'A stiff wire brush removes loose concrete, dirt, and debris from inside the crack. This is critical for adhesion of the patching material.' },
      { n: 'Cold Chisel (3/4")', e: '\u{1F9F1}', r: 'Required', tip: 'Use to widen narrow cracks into an inverted "V" shape (wider at the bottom). This helps the patching compound lock in mechanically. Wear safety glasses.' },
      { n: 'Ball Peen Hammer', e: '\u{1F9F1}', r: 'Required', tip: 'Pair with the cold chisel for crack preparation. Tap gently — you\'re widening the crack, not demolishing the slab.' },
      { n: 'Margin Trowel', e: '\u{1F9F1}', r: 'Required', tip: 'A small margin trowel (5") is perfect for working patching compound into cracks and smoothing the surface flush with the surrounding concrete.' },
      { n: 'Safety Glasses', e: '\u{1F9F1}', r: 'Required', tip: 'Concrete chips fly when chiseling, and bonding agents can splash. Eye protection is essential for all concrete work.' },
    ],
    steps: [
      { s: 'Clean the crack thoroughly with a wire brush, removing all loose concrete, dirt, and debris. Use a shop vac or compressed air to blow out fine particles from deep in the crack.', t: '20 min', photo: true, tip: 'Clean cracks bond better. If the crack has weeds growing in it, remove them completely and apply a non-selective herbicide a few days before repair to kill the roots.' },
      { s: 'For cracks wider than 1/4 inch, use a cold chisel and hammer to undercut the edges, creating an inverted "V" profile that\'s wider at the bottom than the top. This locks the patch in place.', t: '30 min', photo: true, tip: 'Wear safety glasses and gloves when chiseling. The inverted "V" is important — if the crack is wider at the top, the patch can pop out over time. Remove all loose material after chiseling.' },
      { s: 'Dampen the crack with water (moist, not puddling). Apply concrete bonding adhesive to all surfaces inside the crack with a brush. This dramatically improves patch adhesion.', t: '10 min', photo: false, tip: 'Don\'t skip the bonding agent — it\'s the difference between a patch that lasts years and one that pops out in months. Apply when the crack is damp but not dripping.' },
      { s: 'Mix the concrete patching compound per package directions. Pack it firmly into the crack in layers no more than 1/4 inch thick, allowing each layer to set before adding the next.', t: '30 min', photo: true, tip: 'For deep cracks, use backer rod (foam rope) to fill the bottom before patching. This saves material and prevents the patch from shrinking as it cures. Overfill slightly — it will shrink.' },
      { s: 'Smooth the surface flush with the surrounding concrete using a trowel. For textured surfaces, use a broom or sponge to match the existing finish. Feather the edges for a seamless blend.', t: '20 min', photo: true, tip: 'Match the surrounding surface texture while the patch is still workable. A damp broom dragged across the surface replicates a standard concrete broom finish.' },
      { s: 'Cover the patch with plastic sheeting and keep moist for 24-48 hours to cure properly. After curing, apply concrete sealer over the entire area for a uniform appearance and long-term protection.', t: '10 min', photo: true, tip: 'Concrete that cures too fast (in direct sun or wind) will crack again. The plastic sheeting traps moisture for a slower, stronger cure. Don\'t walk on the patch for at least 24 hours.' },
    ],
    shop: [
      { n: 'Quikrete Concrete Patch Compound', sz: '3.5 lb tub', pr: 998, store: 'Home Depot', sku: '1001385924', stock: 'In Stock', tag: 'essential' },
      { n: 'Quikrete Concrete Bonding Adhesive', sz: '1 qt', pr: 798, store: 'Home Depot', sku: '1001284639', stock: 'In Stock', tag: 'essential' },
      { n: 'Sashco Slab Concrete Caulk', sz: '10.5 oz', pr: 698, store: 'Lowe\'s', sku: '429318', stock: 'In Stock', tag: 'essential' },
      { n: 'Quikrete Concrete Sealer', sz: '1 gallon', pr: 2198, store: 'Lowe\'s', sku: '385294', stock: 'In Stock', tag: 'recommended' },
      { n: 'Frost King Backer Rod', sz: '3/8" x 20 ft', pr: 398, store: 'Home Depot', sku: '1001293847', stock: 'In Stock', tag: 'recommended' },
    ],
    matEst: 5090,
  },
};
